version: "3.8"
services:
  krakend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json:ro
    restart: always
